server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #url: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE  #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**   #断言,路径相匹配的进行路由
           # - After=2021-12-10T00:11:52.580+08:00[Asia/Shanghai]
           # - Cookie=username,zzyy
           # - Header=X-Request-Id,\d+
           # - Query=username, \d+
            - Method=GET
          #filters:
          #  -AddRequestParameter=X-Request_Id,1024 #过滤器工厂会在匹配的请求头上加上一对请求头
        - id: payment_routh2
          #url: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/lb/**   #断言,路径相匹配的进行路由


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka


